### ISSUE TITLE
OCRed standards

### ISSUE THREAD

**Issue by johnwcowan** [schemedoc/rnrs-pdf#1]
You should fetch the RnRS copies from https://github.com/johnwcowan/r7rs-spec/tree/errata/rnrs, because they have been OCRed.

**Comment by lassik** [comment]
The reason I started this repo is to get a non-OCR version of R3RS... OCR files are bulkier, and find and copy/paste don't work as well if at all.

**Comment by lassik** [comment]
I have some generated-from-LaTeX PDF version of R3RS on my computer, with working copy/paste, but I have no recollection of where it's from and didn't find it on the net anymore. This repo aims to have executable documentation of the precise source and steps used to get the PDF.

Now it's done, but the table of contents is blank for some reason, vindicating your cause.

Still, it would be really nice to get a proper conversion from the sources.

**Comment by lassik** [comment]
Here's the working PDF someone made via LaTeX: https://misc.lassi.io/2020/rnrs/r3rs.pdf

The font is slightly crisper than the font in the copy generated by this repo as well. However, it's still not very good.

**Comment by lassik** [comment]
OK, now we're talking! The PDF in this repo now has the table of contents intact. Just had to run LaTeX twice, the first pass generates the TOC.

**Comment by lassik** [comment]
Any opposition to publishing it?
